### ISSUE TITLE
Release tag missing

### ISSUE THREAD

**Issue by tardigradus** [holmrenser/IOGA#14]
Hello,

I would request that you provide a release tag.

It is of great importance to science that research is reproducible and for this it must be clear which version of which software was used to obtain a particular result.

More specifically, for software management systems, such as EasyBuild, which are used by HPC sites, installation of packages can only be automated if programs have well-defined versions. If such automation is in place, it means that users can be provided with software much more quickly (some overstretched administrators could even be unwilling to install software which is hard to integrate into their provisioning mechanism).

**Comment by holmrenser** [comment]
You seem to mix the ability to deploy to HPC systems with reproducible research. I have added the commit that was used for our paper to the readme, so our work can be reproduced. I will not provide a formal release tag, since IOGA was never intended to be run on an HPC and is no longer maintained.

**Comment by tardigradus** [comment]
I do indeed realize there is a difference the ability to deploy to HPC systems the ability to reproduce research, hence my use of two separate paragraphs.  I just don't think using a commit to specify a version is a particularly good alternative to using a tag, given the ease with which a tag can be created. However, if your software is no longer maintained, then the point is moot.
