### ISSUE TITLE
Error running IOGA.py

### ISSUE THREAD

**Issue by kk86bioinfo** [holmrenser/IOGA#5]
Hi, I have an error encountered with IOGA.py. 

<code>
sudo nohup python /opt/IOGA/IOGA.py --reference /opt/IOGA/plant_mitochondria.reference.fasta --forward ../PE1.fastq --reverse ../PE2.fastq --insertsize 250 --threads 40 > mesta-IOGA.log 2> mesta-IOGA.err &
</code>

<code>
Traceback (most recent call last):
  File "/opt/IOGA/IOGA.py", line 432, in <module>
    main(args.reference,args.name,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)

  File "/opt/IOGA/IOGA.py", line 377, in main
    source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)

  File "/opt/IOGA/IOGA.py", line 323, in IOGA_loop
    if len(name.split('/')) == 1:

AttributeError: 'NoneType' object has no attribute 'split'
</code>

**Comment by robur86** [comment]
Hi,

I wanted to compare IOGA to other oranellar assemblers. However, I have encountered the same error. Has the issue been solved?

 ~/Prog/IOGA-master/IOGA.py -r ref.fasta -1 F.fastq -2 R.fastq

/IOGA-master/IOGA_config.json
/IOGA-master/IOGA_config.json
[None] Quality trimming with BBduk
Traceback (most recent call last):
  File "/IOGA-master/IOGA.py", line 432, in <module>
    main(args.reference,args.name,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/IOGA-master/IOGA.py", line 377, in main
    source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/IOGA-master/IOGA.py", line 323, in IOGA_loop
    if len(name.split('/')) == 1:
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by holmrenser** [comment]
This error occurred when the name option (-n, --name) was not defined.
I have added a default option (IOGA_RUN), so the problem should be fixed.
Please do a git pull to get the latest version.
