### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by esud1** [holmrenser/IOGA#7]
Hi there, 

I am interested to try the IOGA for chloroplast assembly, but running into problem in installing the program. 
I could not get both setup_IOGA.py or IOGA.py to run.
Both scripts gave me error messages: 

setup_IOGA.py: 

> Traceback (most recent call last):
>   File "./setup_IOGA.py", line 5, in <module>
>     import wget
> ImportError: No module named wget

IOGA.py:

>   File "./IOGA.py", line 305
>     def IOGA_loop(name=,ref,forward,reverse,insertsize,threads,maxrounds):
>                        ^
> SyntaxError: invalid syntax

May you help me with this? 
Thanks

**Comment by holmrenser** [comment]
The first error means you do not have wget available in python, fix this with the following command ```pip install wget```.

The second error was a typo and should be fixed, please do a ```git pull``` to get the fix.

Let me know if this fixes your problems!

**Comment by esud1** [comment]
Hi there

Thanks for your suggestions. 
It now works fine!
