### ISSUE TITLE
New different installation issue

### ISSUE THREAD

**Issue by angelajmcd** [holmrenser/IOGA#9]
Hi Rens,

I've got IOGA to complete on my laptop and am trying to install it on one of our lab macs but am coming across a different issue. I've installed the dependencies and the paths seem to be set up correctly in the .json file. When I run the help menu, everything looks great. However, on the first iteration, the script stops at/around bbmap (error below). Any ideas on what to do? I don't have any nearby python experts. The computer has python 2.7.10 installed, which is the same as what works for my other computer. Could this be some kind of permissions error? Let me know what you think, and thanks.

Angela

/Applications/IOGA/IOGA_config.json
[MSAG] Quality trimming with BBduk
Iteration 1
[MSAG.1] BBmap
Traceback (most recent call last):
  File "IOGA.py", line 432, in <module>
    main(args.reference, args.name, args.forward, args.reverse, args.threads, args.insertsize, args.maxrounds, args.verbose)
  File "IOGA.py", line 377, in main
    source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "IOGA.py", line 344, in IOGA_loop
    samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
  File "IOGA.py", line 114, in run_bbmap
    plot_coverage(basecov)
  File "IOGA.py", line 121, in plot_coverage
    with open(BBmap_coverage,'rU') as infile:
IOError: [Errno 2] No such file or directory: '/Applications/IOGA/MSAG.1/MSAG.1.basecov.txt'

**Comment by holmrenser** [comment]
I have seen this error before, I will try to reproduce it here. Error handling is still on my wish list, so it might take a few days for me to figure out what is happening here!

**Comment by angelajmcd** [comment]
Hi Rens,

We've installed IOGA on our local supercomputer and the same error came up with bbmap. We configured it to use an external installation of bbmap, probably an older version, and the pipeline now works. This is more of an fyi for others than an actual fix... but I thought I'd let you know.
